### ISSUE TITLE
get door of cards read

### ISSUE THREAD

**Issue by IsaacBreuer** [uhppoted/uhppoted-app-home-assistant#13]
Hi,

I’ve been using this project for a couple of months, and it’s fantastic! I really appreciate the work that has gone into it.

I wanted to ask if there’s a way to include the door information in the uhppoted.card.{card}.swipe.event.

I’ve created some sensors based on card reads and event statuses to list all card reads. However, I’m struggling to associate card read events with specific doors.

I can see that this information is definitely provided by the system, as it appears in the iCCard3000.mdb under F-readerID and FreaderNo.

Would it be possible to expose this data as part of the event, or status of other sensors, ( i cant relay on door unlock sensor as  this sensor stays unlocked for a while till its getting back to Locked time, not sure why, ) 

Thanks!

**Comment by uhppoted** [comment]
Oh .. so glad you're finding it useful! It's still got a *long* way to go .. but if you haven't been locked out that's probably good :-).

re. card swipe. I've just taken a quick and as far as I can see it should be fairly straightforward to decorate the swipe event. Presumably you would want at least:
- controller ID
- controller name
- door number
- door name

Anything else?

re. locked event. &lt;sigh&gt; sadly the controller actually only sends an _unlocked_ event. The _locked_ event is synthesized from the polled data so it's a bit iffy. And sluggish .. I'll put it on the "to think about" list - there might be a way to do it better.

**Comment by IsaacBreuer** [comment]
Yes controller ID, controller name, door number and door name is probably enough for the card events


Speaking of event decorations, all events are just logged as detected and event , for instance the controller event , we can probably use some more data there as well.

**Comment by uhppoted** [comment]
Ah, ok, I remember now - there's a reason the events are like they are. Basically _Home Assistant_ doesn't support per event data - at least not out of the box.

It appears there are ways to do it but they're a bit more complicated so it's going to take a little while and some experimentation to see what works - can you clarify your use case? i.e. do you want to:

1. Just do "automation things"
2. Display the events on the dashboard
3. Log events to the logbook
4. ???

**Comment by IsaacBreuer** [comment]
basically i want to have a log for all card reads showing all events in order, witch card which door and was it access granted or denied , i am currently using this with a template sensor so i log all card events to a single sensor and i can see it, but i miss to add the doors to it , see my current template configuration 

template:

  - trigger:
     - platform: state

       entity_id:
        - event.uhppoted_card_isaacpin_swipe_event
        - event.uhppoted_card_worker1pin_swipe_event
        - event.uhppoted_card_18429905_swipe_event
        - event.uhppoted_card_4544641_swipe_event
        - event.uhppoted_card_19437782_swipe_event
        - event.uhppoted_card_8755966_swipe_event
        - event.uhppoted_card_leah_pin_swipe_event
    condition:  "{{ (as_timestamp(now())| int - ( as_timestamp(states(trigger.entity_id)) | int ))<=20 }}" # restricts not to update when reconnecting or reloading the integration , only when there is a real event
    sensor:
        - name: swipes
          state:  "{{ now() }}"  # we set it to current time so it has a change always when there is a change, if we only set the state to the actual state we might miss it as there is no real change, even if attribute change it will not show as a change
          attributes:
           from: "{{ trigger.entity_id }}"
           status:  '{{state_attr(trigger.entity_id,"event_type")}}'
           friendly_name:  '{{state_attr(trigger.entity_id,"friendly_name")}}'

**Comment by uhppoted** [comment]
Ok, that makes things quite a lot easier! 

I have some more testing to do and some cleaning up before I do an interim release - so you're probably looking at early next week sometime. It will only support the template sensor + automation for now - adding it to the _config flow_, etc is a lot more complicated but it can be included in a later release.

**Comment by uhppoted** [comment]
Hi,

I've released interim version _v0.8.10.1_ with a _uhppoted.card.swipe.decorated_ event which has the following information:
```
event_type: uhppoted.card.swipe.decorated
data:
  entity_id: event.uhppoted_card_10058400_swipe_event
  event:
    index: 74
    timestamp: "2025-03-31 10:54:07"
  card:
    card: 10058400
    name: Hermione
  controller:
    id: 405419896
    name: Alpha
  door:
    id: 1
    name: Gryffindor
  access:
    granted: true
    code: 1
    description: swipe valid
...
```

My _template sensor_ looks like this:
```
template:
  - trigger:
      - platform: event
        event_type: uhppoted.card.swipe.decorated
    sensor:
      - name: "Card Swipe"
        unique_id: decorated_card_swipe_sensor
        state: "{{ trigger.event.data.controller.id }}.{{trigger.event.data.event.index}}"
        attributes:
          timestamp: "{{ trigger.event.data.event.timestamp }}"
          card:  "#{{ trigger.event.data.card.card | string }}"
          name: "{{ trigger.event.data.card.name }}"
          controller_id: "{{ trigger.event.data.controller.id | string }}"
          controller_name: "{{ trigger.event.data.controller.name }}"
          door_id: "{{ trigger.event.data.door.id }}"
          door_name: "{{ trigger.event.data.door.name }}"
          access_granted: "{{ 'GRANTED' if trigger.event.data.access.granted else 'DENIED' }}"
          access_code: "{{ trigger.event.data.access.code }}"
          access_description: "{{ trigger.event.data.access.description }}"
```

The combination of `controller.id` and `event.index` is unique for every event , so the _decorated event_ only fires on receiving a new event (i.e. you probably won't need the startup time window thing).

The interim version is on HACS and it's all still very preliminary and experimental but let me know whether this works for your use case.

**Comment by IsaacBreuer** [comment]
Installed 0.8.10.1 but the new entity is not present, not sure how I can find the new uhppoted.card.swipe.decorated, the integration  still shows the same 106 entities as before, tried uninstaling and reinstalling but still not seeing it.

**Comment by uhppoted** [comment]
You won't find it in the entities - you'll need to create a sensor for it (as above).

**Comment by IsaacBreuer** [comment]
Ohh, got it. I thought it's a new event 'entity' like the other event entities you have but with additional data. Going to try it tomorrow

**Comment by IsaacBreuer** [comment]
Works great,  thanks.
For my use case I do 
`
state: "{{ trigger.event.data.card.name}} {{trigger.event.data.door.name}} {{ 'GRANTED' if trigger.event.data.access.granted else 'DENIED' }}"
`

That way I can see logbook of all card swipe with door,card, access

**Comment by uhppoted** [comment]
Great! Thanks for letting me know :-).

re. `state`. You might just want to check that two successive swipe events with the same card + door + granted are logged separately. I've had a case where _HomeAssistant_  only generated events on state changes so it might not if the states for two entirely separate events are the same.

**Comment by IsaacBreuer** [comment]
Yes that's an issue with HA state need to be changed  uniquely to get an update into logs. I'll have to add something unique to statues a timestamp or use  trigger.event.data.event.index  (only having 1 controller at this time) at the end of my status . 

For some mqtt sensors in the past I have used force_update: true, but it's not working for tamplate sensors. Still looking for a better way without concatenating other info to state that I don't really need in the log.

**Comment by uhppoted** [comment]
Hi, just a quick heads up - I've just released v0.8.10.2 (there was a [bug](https://github.com/uhppoted/uhppoted-app-home-assistant/issues/17) in the door lookup code).

Also, the current implementation only generates `uhppoted.card.swipe.decorated` events for configured cards. I'm considering changing it so that it also generates events for unknown cards, but am undecided whether that would be useful or just noise - if you have any thoughts?

_re. HA/events/logging_. It is possible to write directly to the log, e.g.:
```
automation:
  - alias: "Log decorated card swipe event"
    description: "Logs a decorated card swipe to the console"
    trigger:
      platform: event
      event_type: uhppoted.card.swipe.decorated
    action:
      - service: system_log.write
        data_template:
          message: >
            Card swipe: {{ trigger.event.data | to_json }}
          level: info
```

**BUT**, TBH it's a bit of a hack and probably bypasses a whole bunch of useful HA functionality so not sure it's such a good idea.

**Comment by IsaacBreuer** [comment]
not sure if that's a bug, but i see a missed event there is a gap in event index ( 1491 then 1493) in my logs


![Image](https://github.com/user-attachments/assets/0fc6a969-3cfd-4ed0-8eac-4540a023def3)

**Comment by uhppoted** [comment]
Yup, my best guess is that it's most probably a different event e.g. _door-open_ or somesuch. If you have the [_CLI_](https://github.com/uhppoted/uhppote-cli) you can run:

`uhppote-cli get-event 425041860 1492`

to fetch the event and confirm it if you want to be sure.

re. all events. Great! Thanks for the feedback - it looks like _all events_ is going to be the most likely outcome. As you say, it can always be filtered by the template.

**Comment by IsaacBreuer** [comment]
yep the missed events confirmed from cli is cards (usually pins)  that's not resisted and event reason is 6. and i can see the card # used,

**Comment by IsaacBreuer** [comment]
Here is the output for events 1491, 1492, and 1493:


425041860  1491   2025-04-03 15:20:03 4544641      1  true   1  
425041860  1492   2025-04-03 15:54:18 2369         1  false  6  
425041860  1493   2025-04-03 15:54:25 18429905     1  true   1  

I’ve confirmed this multiple times—whenever an unregistered PIN or card is used, the event is not triggered. This aligns with what you mentioned: events are currently only recorded for configured cards.

Since the consensus was to fire events for all access attempts, I believe this should be addressed moving forward.

**Comment by uhppoted** [comment]
Ohhhh - yes, that totally makes sense now that I see it. Thanks!

**Comment by uhppoted** [comment]
Just a quick note to let you know v0.8.10.3 which fires events for all card events has been released, if you want to give it a try.

**Comment by uhppoted** [comment]
Hi,

I'm going to close this issue - I think it's working sufficiently well for your needs? There is still more work I'd like to do on the event handling (e.g. add it to the configuration, etc) but it's out of the scope of this request and will be tracked under a new feature request.

Feel free to reopen it if you need to ..

**Comment by uhppoted** [comment]
No worries - I figured you would let know if there was a problem :-).
